#!/bin/bash
#
# http://github.com/mitchweaver/bin
# 
# dmenu launcher, with my patches
#
# see: http://github.com/mitchweaver/suckless
#

# A messy & pathetic script to launch rofi with xrdb colours
# Cheers! addy

getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}

# Only use the function above if the cache of paintee couldn't be found
if [ -e ~/.cache/paintee ]; then
	. ~/.cache/paintee
	else
	getcolors
fi

colors="-nb $BACKGROUND -nf $CYAN -sb $BLUE -sf $BLACK" 

res=$(xrandr --nograb --current | awk '/\*/ {print $1}')
IFS=' ' read -a res <<< "${res}"
#res=set -- $res
sw=${res[0]%x*}
sh=${res[0]#*x}
#sw=${sw##* }
#sh=${sh%%* }

#echo $sw
#echo $sh

w=$((sw / 2))
x=$((sw / 2 - w / 2))
y=$((sh / 5))
h=$((sh / 50))


[ "$1" = "run" ] &&
    { shift ; _run=_run ; }


dmenu${_run} -f -l $h $colors -x $x -y $y -wi $w "$@" 
#dmenu_run -f -l $h $colors -x $x -y $y -wi $w "$@" 
